version: = '3.8'

services:
  #zookeeper:
  zookeeper:
    image: bitnami/zookeeper:latest
    restart: always
    ports:
      - "2181:2181"
  #kafka:
  kafka:
    image: wurstmeister/kafka:latest
    restart: always
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper
  #spark
  spark:
    image: bitnami/spark:latest
    restart: always
    environment:
      - SPARK_MODE=master
    ports:
      - "8080:8080"
    depends_on:
      - kafka
  # MinIO ment for local testing
  minio:
    image: minio/minio
    restart: always
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: "admin"
      MINIO_ROOT_PASSWORD: "password"
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data

  #postgres
  postgres:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: analytics
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # dbt

  dbt:
    image: ghcr.io/dbt-labs/dbt-postgres:1.6.0
    restart: always
    volumes:
      - ./dbt:/dbt
    depends_on:
      - postgres
    command: ["run"]

    # airflow

  airflow:
    image: apache/airflow:2.6.1
    restart: always
    environment:
      AIRFLOW_CORE_EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
    ports:
      - "8081:8080"
    depends_on:
      - postgres
    command: ["webserver"]

  # grafana
  grafana:
    image: grafana/grafana:latest
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - kafka

# to prevent data loss when restarting container
volumes:
  minio_data:
  postgres_data:
